config/routes.rb
Rails.application.routes.draw do
  
  get 'home/about', as: 'home_about'
  root 'home#index'
  devise_for :users
  resources :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :books, dependent: :destroy

  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, :new_book
  before_action :correct_user, only: [:edit, :update]


  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
      flash[:success] = 'Book was successfully created'
      redirect_to book_path(@new_book.id)
    else
      @books = Book.all
      @user = current_user
      redirect_to books_path
    end
  end

  def index
    @books = Book.all
    @user = current_user
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = 'Book was successfully updated'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:success] = 'Book was successfully destroyed.'
    redirect_to books_path
  end

  private

  def new_book
    @new_book = Book.new
  end

  def correct_user
    user = Book.find(params[:id]).user
    if current_user.id != user.id
      redirect_to books_path
    end
  end


  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :find_login_user, :new_book
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'User was successfully updated'
      redirect_to user_path(@user.id)
    else
      redirect_to edit_book_path(@user)
    end
  end

  private

  def find_login_user
    @user = current_user
  end

  def new_book
    @new_book = Book.new
  end

  def correct_user
    user = User.find(params[:id])
    if current_user.id != user.id
      redirect_to user_path(current_user.id)
    end
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <%= @book.errors.count %>errors prohibited this obj from being saved:<br>
    </div>
    <div class="panel-body">
      <ul>
        <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>
      Editing Book
    </h1>

    <%= form_for @book do |f| %>
      <div class="field row">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title, class: 'col-xs-12' %>
      </div>

      <div class="field row">
        <%= f.label :body, "Opinion" %>
        <%= f.text_area :body, class: 'col-xs-12' %>
      </div>

      <div class="actions row">
        <%= f.submit "Update Book", class: 'btn btn-primary col-xs-12' %>
      </div>
    <% end %>

    <div>
      <%= link_to "Show", books_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @new_book.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <%= @new_book.errors.count %>errors prohibited this obj from being saved:<br>
    </div>
    <div class="panel-body">
      <ul>
        <% @new_book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-xs-3">
    <%= render 'layouts/user_info', user: @user %>
    <%= render 'layouts/new_book', book: @new_book %>
  </div>

  <div class="col-xs-9">
    <h1>
      Books
    </h1>

    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>
            Title
          </th>
          <th>
            Opinion
          </th>
        </tr>
      </thead>
      <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: '40x40', class: "pull-left profile-thumb" %>
            <% end %>
          </td>
          <td>
            <%= link_to book.title, book_path(book.id) %>
          </td>
          <td>
            <%= book.body %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/books/show.html.erb
<div class="row">
  <div class="col-xs-3">
    <%= render 'layouts/user_info', user: @user %>
    <%= render 'layouts/new_book', book: @new_book %>
  </div>

  <div class="col-xs-9">
    <h1>
      Book detail
    </h1>

    <table class="table">
      <tbody>
        <tr>
          <td>
            <%= link_to user_path(@user.id) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: '40x40', class: "pull-left profile-thumb" %>
              <br>
              <%= @user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to @book.title, book_path(@book.id) %>
          </td>
          <td>
            <%= @book.body %>
          </td>
          <% if @book.user.id == current_user.id %>
            <td>
              <%= link_to "Edit", edit_book_path(@book.id), class: "btn-sm btn-success" %>
            </td>
            <td>
              <%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %>
            </td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/home/about.html.erb
<h1>Welcome to Bookers!</h1>

app/views/home/index.html.erb
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>
<div class="row">
  <h1>welcome to Bookers !!</h1>

  <p>In Bookers,</p>

  <p>
    you can share and exchange your opinions , inpressions , and emotions
    <br>
    about various books!
  </p>

  <div class="btn-wrapper">
    <div class="row">
      <%= link_to "Log in", new_user_session_path, class: 'btn btn-info col-xs-10 col-xs-offset-1' %>
    </div>

    <div class="row">
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success col-xs-10 col-xs-offset-1' %>
    </div>
  </div>
</div>

app/views/layouts/_new_book.html.erb
<h2>New book</h2>

<%= form_for book do |f| %>
  <div class="row field">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class:"col-xs-12" %>
  </div>

  <div class="row field">
    <%= f.label :body, "Opinion" %>
    <%= f.text_area :body, class:"col-xs-12" %>
  </div>

  <div class="row">
    <%= f.submit "Create Book", class: 'btn btn-primary col-xs-12' %>
  </div>
<% end %>

app/views/layouts/_user_info.html.erb
<h2>
  User info
</h2>

<%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", class: "pull-left profile-thumb" %>

<table class="table">
  <tr>
    <th>
      name
    </th>
    <td>
      <%= user.name %>
    </td>
  </tr>
  <tr>
    <th>
      introduction
    </th>
    <td>
      <%= user.introduction %>
    </td>
  </tr>
</table>
<% if user.id == current_user.id %>
  <%= link_to "Edit", edit_user_path(user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>
<% else %>
  <%= link_to "Edit", user_path(current_user.id), class: 'col-xs-12 btn btn-default glyphicon glyphicon-wrench' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers2</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
            <% if user_signed_in? %>
              <li>
                <%= link_to 'Home', user_path(current_user.id) %>
              </li>
              <li>
                <%= link_to 'Users', users_path %>
              </li>
              <li>
                <%= link_to 'Books', books_path %>
              </li>
              <li>
                <%= link_to "logout", destroy_user_session_path, method: :delete %>
              </li>
            <% else %>
              <li>
                <%= link_to "Home", root_path %>
              </li>
              <li>
                <%= link_to "About", home_about_path %>
              </li>
              <li>
                <%= link_to "sign up", new_user_registration_path %>
              </li>
              <li>
                <%= link_to "login", new_user_session_path %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <main>
      <div class="container alert">
        <% if flash[:success] %>
          <div class="alert alert-success">
            <%= flash[:success] %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </main>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <small>
              <p>
              CopyRight Infratop.inc
              </p>
            </small>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <%= @user.errors.count %>errors prohibited this obj from being saved:<br>
    </div>
    <div class="panel-body">
      <ul>
        <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<h1>User info</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :profile_image , "Image" %>
    <%= f.attachment_field :profile_image %>
  </div>


  <div>
    <%= f.label :introduction, "Introduction" %>
    <%= f.text_area :introduction %>
  </div>


  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-xs-3">
    <%= render 'layouts/user_info', user: @user %>
    <%= render 'layouts/new_book', book: @new_book %>
  </div>

  <div class="col-xs-9">
    <h1>
      Users
    </h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>
            image
          </th>
          <th>
            name
          </th>
          <th>
          </th>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: '40x40', class: "pull-left profile-thumb" %>
          </td>
          <td>
            <%= user.name %>
          </td>
          <td>
            <%= link_to "Show", user_path(user.id) %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <% if notice %>
    <div class="alert alert-success"><%= notice %></div>
  <% end %>
  <div class="col-xs-3">
    <%= render 'layouts/user_info', user: @user %>
    <%= render 'layouts/new_book', book: @new_book %>
  </div>

  <div class="col-xs-9">
    <h1>Books</h1>

    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>
            Title
          </th>
          <th>
            Opinion
          </th>
        </tr>
      </thead>
      <tbody>
      <% @user.books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(@user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: '40x40', class: "pull-left profile-thumb" %>
            <% end %>
          </td>
          <td>
            <%= link_to book.title, book_path(book.id) %>
          </td>
          <td>
            <%= book.body %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>